# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/
relative_permalinks: true

# Setup
title:               Debian LXC
tagline:             'HOWTOs for LXC on Debian'
description:         'A series of HOWTO on how to use latest stable version of <a href="https://linuxcontainers.org/" target="_blank">Linux Containers</a> on Debian, including unprivileged containers'
url:                 http://debian-lxc.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Fajar A. Nugraha
#  url:               https://twitter.com/mdo
  email:             github@fajar.net

# Custom vars
version:             1.0.0
